macos:
  xcode: 13.4.1
resource_class: macos.x86.medium.gen2
working_directory: ~/project/mapbox-maps-ios
steps:
  - checkout-root
  - configure-environment:
      skip-dependencies: true
  - make-docs
  - slack-notify-failure-if-any
