executor: xcode-sdk-min
resource_class: macos.x86.medium.gen2
steps:
  - checkout-root
  - configure-environment:
      skip-dependencies: true
  - install-xcodegen
  - install-python-dependencies
  - run:
      name: Build dynamic SDK
      command: ./package-mapbox-maps.sh static
      working_directory: scripts/release/packager
  - store_artifacts:
      path: scripts/release/packager/MapboxMaps-static.zip
  - run:
      name: Upload to S3
      command: scripts/release/upload-to-registry.sh scripts/release/packager/MapboxMaps-static.zip mobile-maps-ios-static "$VERSION" MapboxMaps-static.zip releases
  - slack-notify-failure-if-any
