executor: xcode-sdk-min
steps:
  - checkout
  - mapbox/add-mapbox-ssh-key
  - checkout-submodule:
      at: mapbox-maps-internal
  - mapbox/github-commit-progress:
      commit: $CIRCLE_SHA1
      repository: mapbox-maps-ios
      token: $MAPBOXCI_GITHUB_USER_TOKEN
      steps:
        - mapbox/add-mapbox-netrc
        - mapbox/add-mapbox-filetoken
        - mapbox/install-mbx-ci
        - generate-sla-tests
        - build-benchmark
        - mapbox/prepare-build-for-device-testing:
            derivedDataPath: benchmark/DerivedData
            outputPath: output
