parameters:
  configuration:
    type: string
    default: "Debug"
  report_failure:
    type: boolean
    default: false
executor: xcode-sdk-min
environment:
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  CONFIGURATION: << parameters.configuration >>
working_directory: ~/project/mapbox-maps-ios
steps:
  - checkout-root
  - configure-environment:
      skip-dependencies: true
  - run:
      name: Building MapboxMaps for simulator
      command: make build-sdk-for-simulator
      no_output_timeout: 5m
  - run:
      name: Building MapboxMaps for device
      command: make build-sdk-for-device
      no_output_timeout: 5m
  - locate-derived-data-directory:
      base_name: $(basename $(pwd))
  - store-logs:
      derived_data_path: $DERIVED_DATA_PATH
  - report-failure:
      report_failure: << parameters.report_failure >>
      message: "build-sdk"
  - store-default-artifacts
