executor: xcode-min
parameters:
  upload-size-metrics:
    type: boolean
steps:
  - checkout
  - mapbox/add-mapbox-ssh-key
  - mapbox/add-mapbox-netrc
  - mapbox/add-mapbox-filetoken
  - mapbox/install-mbx-ci
  - checkout-maps-submodule
  - build-maps-xcframework:
      upload-size-metrics: << parameters.upload-size-metrics >>
