docker:
  - image: cimg/base:stable
steps:
  - parse-release-version-if-available
  - inject-netrc-credentials
  - run:
      name: Wait binaries public access
      command: |
        echo $VERSION
        timeout 3600 bash -c 'while [[ "$(curl -n -s -o /dev/null -w ''%{http_code}'' https://api.mapbox.com/downloads/v2/mobile-maps-ios/releases/ios/$VERSION/MapboxMaps.zip)" != "200" ]]; do sleep 5; done' || false
      no_output_timeout: 60m
  - slack-notify-failure-if-any
