executor: xcode-sdk-min
resource_class: macos.x86.medium.gen2
steps:
  - checkout
  - mapbox/add-mapbox-ssh-key
  - mapbox/install-mbx-ci
  - inject-netrc-credentials
  - run:
      name: Install AWSCLI
      command: pip3 install awscli requests
  - attach_workspace:
      at: workspace
  - run:
      name: Check DeviceFarm results
      command: |
        scripts/devicefarm.py \
          "$AWS_DEVICE_FARM_PROJECT_ARN" \
          --run-arn-file workspace/benchmark_waiter.json \
          --artifacts-dir BenchmarkResults \
          --output benchmark_results.json
  - run:
      name: Parse XCResult
      command: |
        swift run xcparty metrics --path "$CIRCLE_WORKING_DIRECTORY/workspace/metrics.xcresult" \
          -r . \
          --single-run-test-ids "SpecsBenchmark/testStreetsMunichTtrcCold()" \
          --output "$CIRCLE_WORKING_DIRECTORY/ios-maps-carbon-v2.json"
  - store_artifacts:
      path: ios-maps-carbon-v2.json
  - run:
      name: Test failures
      command: swift run xcparty failures "$CIRCLE_WORKING_DIRECTORY/workspace/metrics.xcresult"
      when: on_fail
  - run:
      name: Upload metrics to AWS
      command: |
        gzip ios-maps-carbon-v2.json
        mv ios-maps-carbon-v2.json.gz ios-maps-carbon-v2-${CIRCLE_BUILD_NUM-1}.json.gz
        sh scripts/publish_to_aws.sh mobile_production.performance ios-maps-carbon-v2-${CIRCLE_BUILD_NUM-1}.json.gz
  - slack-notify-failure-if-any
