executor: xcode-latest
steps:
  - checkout:
      path: ~/project
  - configure-environment:
      skip-dependencies: true
  - install-gh
  - attach_workspace:
      at: workspace
  - run:
      name: Create documentation pull requests
      command: |
        unzip workspace/api-docs.zip -d .
        scripts/release/create-docs-prs.sh -p api-docs
  - store-default-artifacts
  - slack-notify-failure-if-any
