parameters:
  project-name:
    description: Project name in SDK Registry.
    type: string
  include-private-sdk:
    description: Whether to include private flavor of SDK to release.
    type: boolean
executor: xcode-latest
steps:
  - checkout-root
  - configure-environment:
      skip-dependencies: true
  - attach_workspace:
      at: workspace
  - run: ls -lGA workspace
  - run:
      name: Create SDK Registry PR
      command: scripts/release/create-api-downloads-pr.sh << parameters.project-name >> "$VERSION"
  - when:
      condition: << parameters.include-private-sdk >>
      steps:
        - run:
            name: Create SDK Registry PR for private SDK
            command: scripts/release/create-api-downloads-pr.sh << parameters.project-name >>-private "$VERSION"-private
  - slack-notify-failure-if-any
