parameters:
  project-name:
    description: Project name in SDK Registry.
    type: string
executor: xcode-latest
steps:
  - checkout-root
  - configure-environment:
      skip-dependencies: true
  - attach_workspace:
      at: workspace
  - run: ls -lGA workspace
  - run:
      name: Create SDK Registry PR
      command: scripts/release/create-api-downloads-pr.sh << parameters.project-name >> "$VERSION"
  - slack-notify-failure-if-any
