parameters:
  project-name:
    description: Project name in SDK Registry.
    type: string
  skip-private-sdk:
    description: Whether to skip private flavor of SDK to release.
    type: boolean
executor: xcode-latest
steps:
  - checkout-root
  - configure-environment:
      skip-dependencies: true
  - install-gh
  - attach_workspace:
      at: workspace
  - run:
      name: List workspace
      command: ls -lGA workspace
  - run:
      name: Upload API docs
      command: |
        unzip -q workspace/api-docs.zip -d .
        python3 -m pip install gitpython
        scripts/release/upload-docs --jazzy-docs api-docs --docc-docs workspace/docc --version "$VERSION"
  - run:
      name: Create SDK Registry PR
      command: SKIP_PRIVATE=<< parameters.skip-private-sdk >> scripts/release/create-api-downloads-pr.sh << parameters.project-name >> "$VERSION"
  - persist_to_workspace:
      root: .
      paths:
        - api-downloads-pr.txt
  - slack-notify-failure-if-any
