parameters:
  create-xcframework-always-run:
    type: boolean
    default: false
  configuration:
    type: string
    default: "Debug"
  report_failure:
    type: boolean
    default: false
executor: xcode-sdk-min
environment:
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  CONFIGURATION: << parameters.configuration >>
resource_class: macos.x86.medium.gen2
working_directory: ~/project/mapbox-maps-ios
steps:
  - checkout-root
  - configure-environment
  - ensure-text-exists-in-commit:
      commit-text: "[create xcframework]"
      always-run: << parameters.create-xcframework-always-run >>
  - install-all-dependencies
  - make-xcframework-bundle:
      bundle_style: "dynamic"
  - store_artifacts:
      path: MapboxMaps.zip
  # - make-xcframework-bundle:
  #     bundle_style: "static"
  # - store_artifacts:
  #     path: MapboxMaps-static.zip
  - report-failure:
      report_failure: << parameters.report_failure >>
      message: "create-xcframework"
