executor: xcode-latest
steps:
  - checkout-root
  - configure-environment:
      skip-dependencies: true
  - install-gh
  - attach_workspace:
      at: workspace
  - run:
      name: Create documentation pull requests
      command: scripts/release/create-docs-prs.sh
  - store-default-artifacts
  - slack-notify-failure-if-any
