executor: xcode-latest
resource_class: macos.x86.medium.gen2
steps:
  - checkout-root
  - run:
      name: Build depsvalidator
      command: swift build --package-path scripts/depsvalidator
  - run:
      name: Run depsvalidator
      command: swift run --package-path scripts/depsvalidator depsvalidator
