executor: xcode-latest
parameters:
  version:
    type: string
    default: ""
steps:
  - checkout-root
  - configure-environment:
      skip-dependencies: true
  - when:
      condition: << parameters.version >>
      steps:
        - build-docc:
            version: << parameters.version >>
            docc_archive_name: MapboxMaps.doccarchive.zip
            output_path: docc
  - build-docc:
      version: latest
      docc_archive_name: MapboxMaps.doccarchive.zip
      output_path: latest
  - store_artifacts:
      path: MapboxMaps.doccarchive.zip
  - persist_to_workspace:
      root: .
      paths:
        - docc
        - latest
  - report-failure:
      report_failure: true
      message: "Failed to generate docc"
