executor: xcode-latest
steps:
  - checkout:
      path: ~/project
  - parse-release-version-if-available
  - run:
      name: Podspec points to the release version
      command: '[[ $(pod ipc spec  MapboxMaps.podspec | jq -r .version) == "$VERSION" ]]'
  - inject-netrc-credentials
  - run:
      name: General podspec check
      command: pod spec lint --verbose --allow-warnings
  - slack-notify-failure-if-any
