parameters:
  device:
    type: string
    default: "iPhone 14"
  xcode:
    type: string
    default: "14.2.0"
  resource_class:
    type: string
    default: macos.m1.medium.gen1
macos:
  xcode: << parameters.xcode >>
resource_class: << parameters.resource_class >>
steps:
  - macos/preboot-simulator:
      device: "<< parameters.device >>"
      version: "16.2"
  - run:
      name: check system log
      command: tail -f /private/var/log/**/*.log
      background: true
  - checkout-root
  - macos/install-rosetta
  - mapbox/install-mbx-ci
  - attach_workspace:
      at: build
  - run:
      name: Run MapboxMaps integration tests on << parameters.device >>  simulator
      command: |
        XCTESTRUN_PATH=$(find build -type f -name 'MapboxMaps_IntegrationTests*.xctestrun' | head -1)
        xcodebuild \
          test-without-building \
          -xctestrun "$XCTESTRUN_PATH" \
          -destination 'platform=iOS Simulator,name=<< parameters.device >>' \
          -resultBundlePath MapboxMapsTests.xcresult | tee -a xcodebuild.log | xcpretty --report junit --output junit.xml

        find "${HOME}/Library/Developer/Xcode/DerivedData" -name '*.profdata' -exec cp {} . \;
  - collect-code-coverage:
      codecov_flag_name: integration
  - run:
      name: Compress XCResult
      command: zip -r MapboxMapsTests.xcresult.zip MapboxMapsTests.xcresult
      when: always
  - store_test_results:
      path: junit.xml
  - store_artifacts:
      path: MapboxMapsTests.xcresult.zip
  - store_artifacts:
      path: xcodebuild.log
  - store_artifacts:
      path: ~/Library/Logs/DiagnosticReports
  - slack-notify-failure-if-any
