parameters:
  destination:
    type: string
    default: "name=iPhone 14"
  xcode:
    type: string
    default: "14.0.1"
  resource_class:
    type: string
    default: macos.m1.large.gen1
macos:
  xcode: << parameters.xcode >>
resource_class: << parameters.resource_class >>
steps:
  - checkout:
      path: ~/project
  - attach_workspace:
      at: build
  - run:
      name: Run MapboxMaps integration tests on << parameters.destination >>  simulator
      command: |
        XCTESTRUN_PATH=$(find build -type f -name 'MapboxMaps_IntegrationTests*.xctestrun' | head -1)
        xcodebuild \
          test-without-building \
          -xctestrun "$XCTESTRUN_PATH" \
          -parallel-testing-enabled NO \
          -destination 'platform=iOS Simulator,<< parameters.destination >>' \
          -resultBundlePath MapboxMapsTests.xcresult | tee -a xcodebuild.log | xcpretty --report junit --output junit.xml

        find "${HOME}/Library/Developer/Xcode/DerivedData" -name '*.profdata' -exec cp {} . \;
  - collect-code-coverage:
      codecov_flag_name: integration
  - run:
      name: Compress XCResult
      command: zip -r MapboxMapsTests.xcresult.zip MapboxMapsTests.xcresult
      when: always
  - store_test_results:
      path: junit.xml
  - store_artifacts:
      path: MapboxMapsTests.xcresult.zip
  - store_artifacts:
      path: xcodebuild.log
  - store_artifacts:
      path: ~/Library/Logs/DiagnosticReports
  - report-failure:
      message: "Integration test failed: << parameters.destination >>, Xcode: << parameters.xcode >>"
