executor: xcode-latest
steps:
  - checkout:
      path: ~/project
  - install-mbx-ci
  - install-gh
  - run:
      name: Check for up-to-date LICENSE.md
      command: |
        export GITHUB_TOKEN=$(mbx-ci github reader token)
        EXPECTED_LICENSE=$(scripts/license/generate-license.sh)

        if [[ "$(cat LICENSE.md)" == "$EXPECTED_LICENSE" ]];
        then
          echo "LICENSE.md is up-to-date"
          exit 0
        else
          echo "LICENSE.md is not up-to-date.\n\nExpected LICENSE.md:"
          echo "$EXPECTED_LICENSE"
          exit 1
        fi
