executor: xcode-latest
steps:
  - checkout-root
  - run: brew install swiftlint
  - run: swiftlint lint --strict --reporter junit | tee result.xml
  - store_artifacts:
      path: result.xml
  - store_test_results:
      path: result.xml
