executor: xcode-sdk-min
resource_class: macos.x86.medium.gen2
steps:
  - checkout
  - mapbox/install-mbx-ci
  - run:
      name: Push git subtree changes
      command: |
        GITHUB_TOKEN=$(mbx-ci github writer public token)
        git subtree push --prefix=mapbox-maps-ios "https://x-access-token:$GITHUB_TOKEN@github.com/mapbox/mapbox-maps-ios.git" "$CIRCLE_BRANCH"
