docker:
  - image: cimg/base:stable
steps:
  - run:
      name: Run Workflow
      command: |
        RUN_TESTS=false

        if [[ $CIRCLE_BRANCH == "main" || -n $CIRCLE_TAG ]]; then
          RUN_TESTS=true
        fi

        curl -X POST "https://circleci.com/api/v2/project/github/mapbox/mapbox-maps-ios-internal/pipeline" \
              -H 'Content-Type: application/json' \
              -H "Circle-Token: $CIRCLECI_API_TOKEN" \
              -d $'{
            "branch": "main",
            "parameters": {
              "maps-ios-checkout-reference": "<< pipeline.git.revision >>",
              "run-tests": '$RUN_TESTS'
            }
          }'
