parameters:
  report_failure:
    type: boolean
    default: false
executor: xcode-latest
steps:
  - run:
      # TODO: main by default (this is set as a filter), other commits on-demand
      name: Trigger metrics
      command: |
        if [ -n "${CIRCLECI_API_TOKEN}" ]; then
          curl --fail -X POST --header "Content-Type: application/json" --data "{\"parameters\":{\"run_ios_maps_v10_benchmark\":true,\"ci_ref\":${CIRCLE_BUILD_NUM},\"mapbox_hash\":\"${CIRCLE_SHA1}\",\"target_branch\":\"${CIRCLE_BRANCH}\"},\"branch\":\"master\"}" https://circleci.com/api/v2/project/github/mapbox/mobile-metrics/pipeline?circle-token=${CIRCLECI_API_TOKEN}
        else
          echo "CIRCLECI_API_TOKEN not provided"
        fi
  - report-failure:
      report_failure: << parameters.report_failure >>
      message: "metrics"
