parameters:
  turf-revision:
    type: string
    default: ""
macos:
  xcode: "13.1.0"
environment:
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  CONFIGURATION: "Debug"
resource_class: macos.x86.medium.gen2
steps:
  - checkout:
      path: ~/project
  - configure-environment:
      skip-dependencies: true
  - turf-report-pending:
      turf-revision: << parameters.turf-revision >>
  - run:
      name: Set Turf Revision
      command: |
        sed -i '' 's/turf-swift.git", from: "2.0.0"/turf-swift.git", .revision("<< parameters.turf-revision >>")/' Package.swift
  # Building and testing are split into 2, with the aim that we'll be able to reuse
  # the build product and test on multiple simulators
  - run:
      name: Building MapboxMaps for simulator
      command: make build-sdk-for-testing-simulator
      no_output_timeout: 5m
  - run:
      name: Testing MapboxMaps with simulator
      command: make test-sdk-without-building-simulator
  - run:
      name: Compress XCResult
      command: zip -r MapboxMapsTests.xcresult.zip MapboxMapsTests.xcresult
      when: always
  - store_artifacts:
      path: MapboxMapsTests.xcresult.zip
  - locate-derived-data-directory:
      base_name: $(basename $(pwd))
  - store-logs:
      artifact_name: MapboxMaps
      derived_data_path: $DERIVED_DATA_PATH
  - turf-report-success:
      turf-revision: << parameters.turf-revision >>
  - turf-report-failure:
      turf-revision: << parameters.turf-revision >>
