executor: xcode-latest
steps:
  - checkout-root
  - configure-environment:
      skip-dependencies: true
  - attach_workspace:
      at: .
  - run:
      name: Create documentation pull requests
      command: |
        scripts/release/create-docs-prs.sh -sep latest
      environment:
        VERSION: latest
        GIT_CURL_VERBOSE: 2
        GIT_TRACE: 2
        GIT_SSH_COMMAND: "ssh -vvv"
        GIT_TRACE_PERFORMANCE: 2
        GIT_TRACE_PACK_ACCESS: 2
        GIT_TRACE_PACKET: 2
        GIT_TRACE_PACKFILE: 2
        GIT_TRACE_SETUP: 2
        GIT_TRACE_SHALLOW: 2
  - report-failure:
      report_failure: true
      message: "Failed to upload docc"
