description: <
  This job is designed to be called on daily bases.
  It is validating dependency managers integration per branch version rule.
  However, this job would run exclusively for open PRs to the release branches (aka "release/v.*"")
executor: xcode-latest
resource_class: macos.x86.medium.gen2
steps:
  - checkout-root
  - configure-environment:
      skip-dependencies: true
  - install-xcodegen
  - run:
      name: Validate SPM and CocoaPods integrations for current branch
      command: scripts/validate-integrations/validate-integrations.sh -b $CIRCLE_BRANCH
  - store-default-artifacts
