---
name: MapboxMaps
options:
  bundleIdPrefix: com.mapbox
  settingPresets: project
  deploymentTarget:
    iOS: 11.0
settings:
  DEVELOPMENT_TEAM: GJZR2MEM28
  TARGETED_DEVICE_FAMILY: 1,2
targets:
  MapboxMaps:
    templates:
      - dynamicFramework
    dependencies:
      - target: MapboxCoreMaps/MapboxCommon
      - target: MapboxCoreMaps/MapboxCoreMaps
      - target: Turf/Turf
      - target: MME/MapboxMobileEvents
    scheme:
      testTargets:
        - MapboxMapsTests

  MapboxMapsTests:
    templates:
      - installTokenScript
      - hostApplication
      - unitTest
    sources:
      - path: "build/${PROJECT}/Tests/MapboxMapsTests"
        excludes:
          - "Integration Tests/HTTP/HTTPIntegrationTests.swift"
    dependencies:
      - target: Examples
      - target: "CocoaImageHashing/CocoaImageHashing (iOS Framework)"

  MapboxMapsHTTPTests:
    templates:
        - installTokenScript
        - hostApplication
        - unitTest
    sources:
      - path: "build/${PROJECT}/Tests/MapboxMapsTests"
        includes:
          - Integration Tests/HTTP/HTTPIntegrationTests.swift
          - Integration Tests/MapViewIntegrationTestCase.swift
          - Integration Tests/IntegrationTestCase.swift
          - Helpers/Bundle+MapboxMapsTests.swift
          - Helpers/String+FileSystemSafe.swift
          - Helpers/XCTestCase+GuardForMetalDevice.swift
          - Helpers/XCTestCase+MapboxAccessToken.swift
          - Helpers/XCTestCase+TemporaryCacheDirectory.swift
    dependencies:
      - target: Examples
      - target: "CocoaImageHashing/CocoaImageHashing (iOS Framework)"

  Examples:
    templates:
      - installTokenScript
      - assetCatalog
      - application
    type: application
    platform: iOS
    settings:
      SKIP_INSTALL: NO
      INFOPLIST_FILE: "build/${PROJECT}/Apps/Examples/Examples/Info.plist"
    scheme:
      testTargets:
        - ExamplesTests
        - MapboxMapsTests
        - MapboxMapsHTTPTests
    sources:
      - path: build/${PROJECT}/Apps/Examples/Examples/

  ExamplesTests:
    templates:
      - hostApplication
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: build/${PROJECT}/Apps/Examples/ExamplesTests/
    dependencies:
      - target: Examples

  StressTestApp:
    deploymentTarget: 13.0
    templates:
      - installTokenScript
      - assetCatalog
      - application
    sources:
      - path: build/${PROJECT}/Apps/StressTest/StressTest/

targetTemplates:
  installTokenScript:
    postBuildScripts:
      - path: build/${PROJECT}/scripts/insert_access_token.sh
        name: Insert Mapbox Token
        inputFiles:
          - $(TARGET_BUILD_DIR)/$(INFOPLIST_PATH)
  assetCatalog:
    settings:
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
  hostApplication:
    settings:
      BUNDLE_LOADER: $(TEST_HOST)
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/Examples.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Examples
  application:
    type: application
    platform: iOS
    settings:
      LD_RUNPATH_SEARCH_PATHS: $(inherited) @executable_path/Frameworks
    dependencies:
      - target: MapboxCoreMaps/MapboxCommon
      - target: MapboxCoreMaps/MapboxCoreMaps
      - target: Turf/Turf
      - target: MME/MapboxMobileEvents
      - target: MapboxMaps
  unitTest:
      type: bundle.unit-test
      platform: iOS
      configFiles:
        Debug: build/${PROJECT}/Configurations/unitTests.xcconfig
        Release: build/${PROJECT}/Configurations/unitTests.xcconfig
  dynamicFramework:
    type: framework
    platform: iOS
    configFiles:
      Debug: build/${PROJECT}/Configurations/base.xcconfig
      Release: build/${PROJECT}/Configurations/base.xcconfig
    settings:
      DYLIB_INSTALL_NAME_BASE: "@rpath"
      MACH_O_TYPE: mh_dylib
      DEFINES_MODULE: "YES"
      PRODUCT_NAME: $(TARGET_NAME:c99extidentifier)
      INFOPLIST_FILE: "build/${PROJECT}/Sources/${target_name}/Info.plist"
    sources:
      - path: "build/${PROJECT}/Sources/${target_name}/"
projectReferences:
  Turf:
    path: "build/turf-swift/Turf.xcodeproj"
  MME:
    path: "build/mapbox-events-ios/MapboxMobileEvents.xcodeproj"
  MapboxCoreMaps:
    path: "build/mapbox-gl-native-internal/build/ios/Mapbox GL Native.xcodeproj"
  CocoaImageHashing:
    path: "build/cocoaimagehashing/CocoaImageHashing.xcodeproj"
