---
name: MapboxMaps
options:
  bundleIdPrefix: com.mapbox
  settingPresets: project
  groupOrdering:
    - order:
      - General
      - Examples
      - DebugApp
      - MapboxMaps
      - MapboxMapsTests
  deploymentTarget:
    iOS: 12.0
packages:
  Fingertips:
    url: git@github.com:mapbox/Fingertips.git
    from: 0.6.0
settings:
  DEVELOPMENT_TEAM: GJZR2MEM28
  TARGETED_DEVICE_FAMILY: 1,2
targets:
  MapboxMaps:
    templates:
      - dynamicFramework
    dependencies:
      - target: MapboxCoreMaps/MapboxCommon
      - target: MapboxCoreMaps/MapboxCoreMaps
      - target: Turf/Turf
    scheme:
      testTargets:
        - MapboxMapsTests
    sources:
      - path: ../mapbox-maps-ios
        includes:
          - CHANGELOG.md
          - Package.swift
          - Makefile
          - LICENSE.md
        buildPhase: none
        group: General
      - path: .
        includes:
          - generate-debuggable-environment
          - project.yml
        group: General

  MapboxMapsTests:
    templates:
      - installTokenScript
      - hostApplication
      - unitTest
    sources:
      - path: "../mapbox-maps-ios/Tests/MapboxMapsTests"
        excludes:
          - "Integration Tests/HTTP/HTTPIntegrationTests.swift"
    dependencies:
      - target: Examples
    settings:
      INFOPLIST_FILE: "../mapbox-maps-ios/Tests/MapboxMapsTests/Info.plist"

  MapboxMapsHTTPTests:
    templates:
        - installTokenScript
        - hostApplication
        - unitTest
    sources:
      - path: "../mapbox-maps-ios/Tests/MapboxMapsTests"
        includes:
          - Integration Tests/HTTP/HTTPIntegrationTests.swift
          - Integration Tests/MapViewIntegrationTestCase.swift
          - Integration Tests/IntegrationTestCase.swift
          - Helpers/Bundle+MapboxMapsTests.swift
          - Helpers/String+FileSystemSafe.swift
          - Helpers/XCTestCase+GuardForMetalDevice.swift
          - Helpers/XCTestCase+MapboxAccessToken.swift
          - Helpers/XCTestCase+TemporaryCacheDirectory.swift
    dependencies:
      - target: Examples

  Examples:
    templates:
      - installTokenScript
      - assetCatalog
      - application
    type: application
    platform: iOS
    settings:
      SKIP_INSTALL: NO
      INFOPLIST_FILE: "../mapbox-maps-ios/Apps/Examples/Examples/Info.plist"
    scheme:
      testTargets:
        - ExamplesTests
        - MapboxMapsTests
        - MapboxMapsHTTPTests
      environmentVariables:
        - variable: MTL_HUD_ENABLED
          value: 1
        - variable: MAPBOX_MAPS_SIGNPOSTS_ENABLED
          value: 1
          isEnabled: false
        - variable: MAPBOX_REOPEN_EXAMPLE
          value: 1
    sources:
      - path: ../mapbox-maps-ios/Apps/Examples/Examples/
  DebugApp:
    templates:
      - installTokenScript
      - assetCatalog
      - application
    type: application
    platform: iOS
    settings:
      SKIP_INSTALL: NO
      INFOPLIST_FILE: "../mapbox-maps-ios/Apps/DebugApp/DebugApp/Info.plist"
      IPHONEOS_DEPLOYMENT_TARGET: 13.0
    sources:
      - path: ../mapbox-maps-ios/Apps/DebugApp/DebugApp/
    scheme:
      environmentVariables:
        - variable: MTL_HUD_ENABLED
          value: 1
        - variable: MAPBOX_MAPS_SIGNPOSTS_ENABLED
          value: 1
          isEnabled: false
        - variable: MAPBOX_REOPEN_EXAMPLE
          value: 1

  ExamplesTests:
    templates:
      - hostApplication
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: ../mapbox-maps-ios/Apps/Examples/ExamplesTests/
    dependencies:
      - target: Examples
    settings:
      INFOPLIST_FILE: "../mapbox-maps-ios/Apps/Examples/ExamplesTests/Info.plist"

  StressTestApp:
    deploymentTarget: 13.0
    templates:
      - installTokenScript
      - assetCatalog
      - application
    sources:
      - path: ../mapbox-maps-ios/Apps/StressTest/StressTest/

targetTemplates:
  installTokenScript:
    settings:
      base:
        INFOPLIST_PREFIX_HEADER: $(DERIVED_FILE_DIR)/InfoPlist.Prefix.h
        INFOPLIST_PREPROCESS: YES
    preBuildScripts:
      - path: ../mapbox-maps-ios/scripts/insert_access_token.sh
        name: Insert Mapbox Access Token
        outputFiles:
          - $(INFOPLIST_PREFIX_HEADER)
  assetCatalog:
    settings:
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
  hostApplication:
    settings:
      BUNDLE_LOADER: $(TEST_HOST)
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/Examples.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Examples
  application:
    type: application
    platform: iOS
    settings:
      LD_RUNPATH_SEARCH_PATHS: $(inherited) @executable_path/Frameworks
    dependencies:
      - target: MapboxCoreMaps/MapboxCommon
      - target: MapboxCoreMaps/MapboxCoreMaps
      - target: Turf/Turf
      - target: MapboxMaps
      - package: Fingertips

  unitTest:
      type: bundle.unit-test
      platform: iOS
      configFiles:
        Debug: ../mapbox-maps-ios/Configurations/unitTests.xcconfig
        Release: ../mapbox-maps-ios/Configurations/unitTests.xcconfig
  dynamicFramework:
    type: framework
    platform: iOS
    configFiles:
      Debug: ../mapbox-maps-ios/Configurations/base.xcconfig
      Release: ../mapbox-maps-ios/Configurations/base.xcconfig
    settings:
      DYLIB_INSTALL_NAME_BASE: "@rpath"
      MACH_O_TYPE: mh_dylib
      DEFINES_MODULE: "YES"
      PRODUCT_NAME: $(TARGET_NAME:c99extidentifier)
      INFOPLIST_FILE: "../mapbox-maps-ios/Sources/${target_name}/Info.plist"
    sources:
      - path: "../mapbox-maps-ios/Sources/${target_name}/"
projectReferences:
  Turf:
    path: "build/turf-swift/Turf.xcodeproj"
  MapboxCoreMaps:
    path: "build/mapbox-gl-native-internal/build/ios/Mapbox GL Native.xcodeproj"
