# Configuration for probot-stale - https://github.com/probot/stale

# Set to true to ignore issues in a project (defaults to false)
exemptProjects: true
# Set to true to ignore issues in a milestone (defaults to false)
exemptMilestones: true

# Label to use when marking as stale
staleLabel: archived

# Limit the number of actions per hour, from 1-30. Default is 30
limitPerRun: 1

# SEMVER-MAJOR - @tobrun
# Issues or Pull Requests with these labels will never be considered stale. Set to `[]` to disable
exemptLabels:
  - SEMVER-MAJOR

pulls:
  daysUntilStale: 120
  daysUntilClose: -1
  markComment: false
  closeComment: >
    This pull request has been automatically detected as stale because it has not had
    recent activity and will be archived. Thank you for your contributions.

issues:
  daysUntilStale: 240
  daysUntilClose: -1
  markComment: false
  closeComment: >
    This issue has been automatically detected as stale because it has not had
    recent activity and will be archived. Thank you for your contributions.
