---
name: MapboxMapsDebug
packages:
  MapboxMobileEvents:
    url: "https://github.com/mapbox/mapbox-events-ios.git"
    exactVersion: "1.0.2"
targets:
  MapboxMapsDebug:
    type: framework
    platform: iOS
    settings:
      base:
        INFOPLIST_FILE: "mapbox-maps-ios/Sources/MapboxMaps/MapView/Info.plist"
        PRODUCT_BUNDLE_IDENTIFIER: com.mapbox.MapboxMaps
        INSTALL_PATH: $(LOCAL_LIBRARY_DIR)/Frameworks
        SKIP_INSTALL: "NO"
        TARGETED_DEVICE_FAMILY: 1,2
        DYLIB_COMPATIBILITY_VERSION: 1
        DYLIB_CURRENT_VERSION: 3
        LD_RUNPATH_SEARCH_PATHS: $(inherited) @executable_path/Frameworks @loader_path/Frameworks
        MACH_O_TYPE: mh_dylib
        DEFINES_MODULE: "YES"
        PRODUCT_NAME: $(TARGET_NAME:c99extidentifier)
        CODE_SIGN_STYLE: Automatic
        BUILD_DIR: .build
    configFiles:
      Debug: "mapbox-maps-ios/Mapbox/Configurations/Mapbox.xcconfig"
      Release: "mapbox-maps-ios/Mapbox/Configurations/Mapbox.xcconfig"
    sources:
      - path: "mapbox-maps-ios/Sources/MapboxMaps/"
        includes: "*.swift"
        excludes:
          - "**/*.plist"
          - "**/*.h"
      - path: "mapbox-maps-ios/Sources/MapboxMaps/MapView/Info.plist"
      - path: "mapbox-maps-ios/Sources/MapboxMaps/MapView/MapboxMaps.h"
    dependencies:
      - framework: "./MapboxCoreMaps.framework"
      - framework: "./MapboxCommon.framework"
      - framework: "./Turf.framework"
      - package: MapboxMobileEvents
