# yaml-language-server: $schema=https://raw.githubusercontent.com/Kila2/XcodeGen/master/Assets/json-schema/project.json
name: MapboxMaps
include:
  - xcodegen/Examples.yml
  - xcodegen/MapboxMaps.yml
  - xcodegen/MapboxMapsTests.yml
settings:
  base:
    MAPBOXMAPS_PATH: .
options:
  bundleIdPrefix: com.mapbox
  defaultConfig: Release
  xcodeVersion: "15.0"
  parallelizeBuild: false
  groupOrdering:
    - order:
      - General
      - Examples
      - DebugApp
      - MapboxMaps
      - MapboxMapsTests
  preGenCommand: scripts/prepare_binary_dependencies.sh

packages:
  Fingertips:
    url: git@github.com:mapbox/Fingertips.git
    from: 0.6.0
  Hammer:
    url: git@github.com:lyft/Hammer.git
    from: 0.14.3

targets:
  Examples:
    templates:
      - swiftlintScript
      - maps-dependencies
    settings:
      base:
        SWIFT_OBJC_BRIDGING_HEADER: Apps/Examples/Examples/Examples-Bridging-Header.h
      groups:
        - turf_library_evolution_settings
    dependencies:
      - target: MapboxMaps
      - package: Fingertips
    scheme:
      testTargets:
        - MapboxMapsTests
      gatherCoverageData: true
      coverageTargets:
        - MapboxMaps

  MapboxMaps:
    settings:
      base:
        RUN_DOCUMENTATION_COMPILER: YES
        OTHER_DOCC_FLAGS: "--warnings-as-errors"