parameters:
  commit-text:
    type: string
  always-run:
    type: boolean
steps:
  - run:
      name: Check for "<< parameters.commit-text >>" in commit message
      command: |
        export RUN_JOB="$(git log -1 --pretty=%B | fgrep "<< parameters.commit-text >>" | wc -l)"
        if << parameters.always-run >>; then
          echo "Job configured to always run"
        elif [[ "$RUN_JOB" -ne "0" ]]; then
          echo "<< parameters.commit-text >> found."
        else
          echo "Skipping job"
          circleci-agent step halt
        fi
