steps:
  - run:
      name: Injecting Mapbox public token
      command: |
        echo "MAPBOX_ACCESS_TOKEN = ${MAPBOX_ACCESS_TOKEN}" > ./developer.xcconfig
        echo "${MAPBOX_ACCESS_TOKEN}" > ~/.mapbox
        echo "${MAPBOX_ACCESS_TOKEN}" > ./Tests/MapboxMapsTests/Helpers/MapboxAccessToken
