steps:
  - run:
      name: Compress default artifacts
      command: |
        CURRENT_DIR=$(pwd)
        cd $DEFAULT_ARTIFACTS_DIR
        zip -yr "$CURRENT_DIR/artifacts.zip" . || true
      when: always
  - store_artifacts:
      path: artifacts.zip
