parameters:
  artifact_name:
    type: string
    default: "firebase"
  derived_data_path:
    type: string
    default: "build"
description: "Save firebase Results as Artifacts"
steps:
  - run:
      name: Zipping firebase results
      command: |
        export ZIP_FILE="$PWD/<< parameters.artifact_name >>.zip"
        cd "<< parameters.derived_data_path >>"
        zip -r "$ZIP_FILE" xcodebuild_output.log || echo "Skipping xcodebuild_output.log"
        zip -r "$ZIP_FILE" video.mp4 || echo "Skipping video.mp4"
        zip -r "$ZIP_FILE" test_result_0.xml || echo "Skipping test_result_0.xml"
        zip -r "$ZIP_FILE" syslog.txt || echo "Skipping syslog.txt"
        zip -r "$ZIP_FILE" TestLogs || echo "Skipping TestLogs"
        zip -r "$ZIP_FILE" ProfileData || echo "Skipping ProfileData"
        zip -r "$ZIP_FILE" CrashLogs || echo "Skipping CrashLogs"
      when: always
  - store_artifacts:
      path: << parameters.artifact_name >>.zip
