parameters:
  artifact_name:
    type: string
    default: "build"
  derived_data_path:
    type: string
    default: "build"
description: "Save Logs as Artifacts"
steps:
  - run:
      name: Zipping logs
      command: |
        export ZIP_FILE="$PWD/<< parameters.artifact_name >>.zip"
        cd "<< parameters.derived_data_path >>"
        zip -r "$ZIP_FILE" Build/Products || echo "Skipping Build/Products"
        zip -r "$ZIP_FILE" Build/ProfileData || echo "Skipping Build/ProfileData"
        zip -r "$ZIP_FILE" Logs || echo "Skipping Logs"
      when: always
  - store_artifacts:
      path: << parameters.artifact_name >>.zip
