parameters:
  turf-revision:
    type: string
steps:
  - run:
      name: Set Turf commit status to success
      command: |
        curl --request POST \
          --url https://api.github.com/repos/mapbox/turf-swift/statuses/<< parameters.turf-revision >> \
          --header 'Accept: application/vnd.github.v3+json' \
          --header "Authorization: token $(mbx-ci github notifier token)" \
          --data "{\"state\":\"success\",\"target_url\":\"$CIRCLE_BUILD_URL\",\"description\":\"MapboxMaps SDK integration tests passed\",\"context\":\"Maps SDK Integration\"}"
