# Note: This is a setup config. The real configuration file is split up into separate files in the config subfolder
# and automatically assembled on every build.
version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.3.1

jobs:
  setupci:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Install CircleCI CLI
          command: |
            curl -fLSs https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/v0.1.26255/install.sh | sudo VERSION=0.1.26255 bash
            circleci version
            circleci --help
      - run:
          name: Generate config
          command: circleci config pack .circleci/config > circle.yml
      - run:
          name: Print generated CircleCI config
          command: cat circle.yml
      - continuation/continue:
          configuration_path: circle.yml

workflows:
  setup:
    jobs:
      - setupci:
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+.*/
