# Note: This is a setup config. The real configuration file is split up into separate files in the config subfolder
# and automatically assembled on every build.
version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  setup:
    macos:
      xcode: 14.2.0
    steps:
      - checkout
      - run:
          name: Install CircleCI CLI
          command: brew install circleci
      - run:
          name: Generate config
          command: circleci config pack .circleci/config > circle.yml
      - run:
          name: Show config
          command: cat circle.yml
      - continuation/continue:
          configuration_path: circle.yml

workflows:
  setup:
    jobs:
      - setup