# Note: This is a setup config. The real configuration file is split up into separate files in the config subfolder
# and automatically assembled on every build.
version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  setup:
    docker:
      - image: circleci/circleci-cli:latest
    steps:
      - checkout
      - run:
          name: Generate config
          command: circleci config pack .circleci/config > circle.yml
      - continuation/continue:
          configuration_path: circle.yml

workflows:
  setup:
    jobs:
      - setup
      