# Note: This is a setup config. The real configuration file is split up into separate files in the config subfolder
# and automatically assembled on every build.
version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.3.1

# Parameters you need to passthrough to downstream config
# Please, keep them in sync with .circleci/config/parameters/@parameters.yml
# and "Write repo parameters" step below
parameters:
  turf-revision:
    type: string
    default: ""

jobs:
  setupci:
    docker:
      - image: cimg/python:3.11
    resource_class: small
    environment:
      # Grab latest environment variable at
      # https://platform.mapbox.com/developer-experience/ci-systems/reference/mbx-ci/#setup-authentication-1
      MBX_CI_DOMAIN: o619qyc20d.execute-api.us-east-1.amazonaws.com
    steps:
      - checkout
      - run:
          name: Install mbx-ci
          command: |
            curl -Ls https://mapbox-release-engineering.s3.amazonaws.com/mbx-ci/latest/mbx-ci-linux-amd64 > mbx-ci && chmod 755 ./mbx-ci
      - run:
          name: Install CircleCI CLI
          command: |
            curl -fLSs https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh | sudo bash
      - run:
          name: Install sdk-ci
          command: |
            GITHUB_ACCESS_TOKEN=$(./mbx-ci github reader token)
            pip3 --disable-pip-version-check install https://x-access-token:${GITHUB_ACCESS_TOKEN}@api.github.com/repos/mapbox/sdk-cicd/tarball/develop
      - run:
          name: Pack repo config
          command: |
            circleci config pack .circleci/config > circle.yml
      - run:
          name: Get shared config
          command: |
            sdk-ci circleci get-shared-config -o shared_config.yml
      - run:
          name: Generate config
          command: |
            sdk-ci circleci generate-dynamic-parameters
            sdk-ci yaml merge circle.yml shared_config.yml sdk_ci_parameters.yml -o .circleci/generated_config.yml
      - run:
          name: Show config
          command: cat .circleci/generated_config.yml
      - run:
          name: Validate config
          command: |
            circleci config validate .circleci/generated_config.yml
      - run:
          name: Write repo parameters
          command: |
            cat \<<'EOF' > repo_parameters.json
            {
                "turf-revision": "<< pipeline.parameters.turf-revision >>"
            }
            EOF
      - run:
          name: Merge parameters
          command: |
            sdk-ci json merge sdk_ci_parameters.json repo_parameters.json -o merged_parameters.json
      - run:
          name: Process config
          command: |
            circleci config process .circleci/generated_config.yml --pipeline-parameters merged_parameters.json
      - continuation/continue:
          configuration_path: .circleci/generated_config.yml
          parameters: merged_parameters.json

workflows:
  setup:
    jobs:
      - setupci:
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+.*/
