---
name: MapboxMaps
configFiles:
  Debug: Configurations/base.xcconfig
  Release: Configurations/base.xcconfig
options:
  defaultConfig: Release
  parallelizeBuild: false
packages:
  MapboxMaps:
    path: ./
  Fingertips:
    url: git@github.com:mapbox/Fingertips.git
    from: 0.6.0
  Hammer:
    url: git@github.com:lyft/Hammer.git
    from: 0.14.3
settings:
  base:
    VALIDATE_WORKSPACE: "NO"
    COPY_PHASE_STRIP: "NO"
    GCC_WARN_64_TO_32_BIT_CONVERSION: $(GCC_WARN_64_TO_32_BIT_CONVERSION)
    CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: "YES"
    MTL_FAST_MATH: "YES"
  configs:
    Debug:
      ONLY_ACTIVE_ARCH: "YES"
      DEBUG_INFORMATION_FORMAT: dwarf
      ENABLE_TESTABILITY: "YES"
      MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
    Release:
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
      VALIDATE_PRODUCT: "YES"
      ENABLE_NS_ASSERTIONS: "NO"
      SWIFT_COMPILATION_MODE: wholemodule
      MTL_ENABLE_DEBUG_INFO: "NO"
targets:
  MapboxMapsTestsWithHost:
    templates:
      - installTokenScript
    type: bundle.unit-test
    platform: iOS
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: "YES"
        TARGETED_DEVICE_FAMILY: "1,2"
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @loader_path/Frameworks"
        INFOPLIST_FILE: "Tests/MapboxMapsTests/Info.plist"
        PRODUCT_BUNDLE_IDENTIFIER: "com.mapbox.MapboxTests"
        PRODUCT_NAME: "$(TARGET_NAME)"
        CODE_SIGN_STYLE: "Automatic"
        COMPRESS_PNG_FILES: "NO"
        STRIP_PNG_TEXT: "NO"
    configFiles:
      Debug: Configurations/unitTests.xcconfig
      Release: Configurations/unitTests.xcconfig
    sources:
      - path: "Tests/MapboxMapsTests"
    dependencies:
      - target: MapboxTestHost
  GestureTests:
    templates:
      - installTokenScript
    type: bundle.unit-test
    platform: iOS
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: "YES"
        TARGETED_DEVICE_FAMILY: "1,2"
        INFOPLIST_FILE: "Tests/MapboxMapsTests/Info.plist"
        PRODUCT_BUNDLE_IDENTIFIER: "com.mapbox.MapboxTests"
        PRODUCT_NAME: "$(TARGET_NAME)"
        IPHONEOS_DEPLOYMENT_TARGET: "13.0"
    configFiles:
      Debug: Configurations/unitTests.xcconfig
      Release: Configurations/unitTests.xcconfig
    sources:
      - path: "Tests/MapboxMapsTests"
        includes:
          - "Integration Tests/MapViewIntegrationTestCase.swift"
          - "Integration Tests/IntegrationTestCase.swift"
          - "Helpers/Bundle+MapboxMapsTests.swift"
          - "Helpers/String+FileSystemSafe.swift"
          - "Helpers/XCTestCase+GuardForMetalDevice.swift"
          - "Helpers/XCTestCase+MapboxAccessToken.swift"
          - "Helpers/XCTestCase+TemporaryCacheDirectory.swift"
      - path: Tests/GestureTests
    dependencies:
      - target: MapboxTestHost
      - package: Hammer
    postBuildScripts:
      - script: scripts/run_swiftlint.sh
        name: Run swiftlint
        basedOnDependencyAnalysis: false
        showEnvVars: false

  MapboxTestHost:
    type: application
    platform: iOS
    deploymentTarget: "12.0"
    settings:
      base:
        TARGETED_DEVICE_FAMILY: "1,2"
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"
        INFOPLIST_FILE: "MapboxTestHost/Info.plist"
        PRODUCT_BUNDLE_IDENTIFIER: "com.mapbox.MapboxMapsTestHost"
        PRODUCT_NAME: "$(TARGET_NAME)"
        SYSTEM_FRAMEWORK_SEARCH_PATHS: "$(PLATFORM_DEVELOPER_LIBRARY_DIR)/PrivateFrameworks"
        CODE_SIGN_STYLE: "Automatic"
        ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
        SWIFT_VERSION: "5.0"
    sources:
      - path: MapboxTestHost
    dependencies:
      - package: MapboxMaps
        product: MapboxMaps
      - package: Fingertips
    scheme:
      testTargets:
          - MapboxMapsTestsWithHost
          - GestureTests
      gatherCoverageData: true
targetTemplates:
  installTokenScript:
    settings:
      base:
        INFOPLIST_PREFIX_HEADER: $(DERIVED_FILE_DIR)/InfoPlist.Prefix.h
        INFOPLIST_PREPROCESS: YES
    preBuildScripts:
      - path: scripts/insert_access_token.sh
        name: Insert Mapbox Access Token
        showEnvVars: false
        basedOnDependencyAnalysis: false
        outputFiles:
          - $(INFOPLIST_PREFIX_HEADER)
