unless: << pipeline.parameters.turf-revision >>
jobs:
  - run-tests?:
      type: approval
      filters:
        branches:
          ignore:
            - main
            - develop
  - build-host-tests:
      context:
        - Slack Orb
        - Fastlane Match
        - SDK Registry Token
        - Apple Machine account
        - Maps SDK/Public Mapbox Token
      name: Build MapboxTestHost tests [non-main]
      requires:
        - run-tests?
  - run-firebase-tests:
      context:
        - Slack Orb
        - Maps SDK/Google Cloud credentials
      name: Run MapboxTestHost tests [non-main]
      scheme: MapboxTestHost
      requires:
        - Build MapboxTestHost tests [non-main]
      devices: --device model=iphone8,version=14.7

  - run-examples-tests?:
      type: approval
      filters:
        branches:
          ignore:
            - main
            - develop
  - build-examples-tests:
      context:
        - Slack Orb
        - Fastlane Match
        - SDK Registry Token
        - Apple Machine account
        - Maps SDK/Public Mapbox Token
      name: Build Examples tests [non-main]
      requires:
        - run-examples-tests?
  - run-firebase-tests:
      context:
        - Slack Orb
        - Maps SDK/Google Cloud credentials
      name: Run Examples tests [non-main]
      scheme: Examples
      requires:
        - Build Examples tests [non-main]
      devices: --device model=iphone13pro,version=15.7
