jobs:
  - build-dynamic:
      context:
        - Slack Orb
        - SDK Registry Token
      check-api-breakage: false
      project-name: mobile-maps-ios-preview
      filters:
        tags:
          # matches v11.0.0-alpha
          only: /^v[0-9]+\.[0-9]+\.[0-9]+-alpha.*/
        branches:
          ignore: /.*/
  - create-registry-pr:
      context:
        - Slack Orb
      project-name: mobile-maps-ios-preview
      requires:
        - build-dynamic
      filters:
        tags:
          only: /^v[0-9]+\.[0-9]+\.[0-9]+-alpha.*/
        branches:
          ignore: /.*/
  - wait-registry-pr:
      requires:
        - create-registry-pr
      type: approval
      filters:
        tags:
          only: /^v[0-9]+\.[0-9]+\.[0-9]+-alpha.*/
        branches:
          ignore: /.*/
  - check-registry:
      project-name: mobile-maps-ios-preview
      context:
        - Slack Orb
        - SDK Registry Token
      requires:
        - wait-registry-pr
      filters:
        tags:
          only: /^v[0-9]+\.[0-9]+\.[0-9]+-alpha.*/
        branches:
          ignore: /.*/
