jobs:
  - release-precheck:
      context:
        - Slack Orb
        - SDK Registry Token
      filters:
        tags:
          only: /^v[0-9]+\.[0-9]+\.[0-9]+.*/
        branches:
          ignore: /.*/
  - build-baseline-sdk:
      context:
        - Slack Orb
        - SDK Registry Token
      requires:
        - release-precheck
  - build-dynamic:
      context:
        - Slack Orb
        - SDK Registry Token
      requires:
        - release-precheck
  - build-static:
      context:
        - Slack Orb
        - SDK Registry Token
      requires:
        - release-precheck
  - build-docs:
      context:
        - Slack Orb
        - SDK Registry Token
      requires:
        - release-precheck
  - build-studio-preview:
      context:
        - Slack Orb
        - SDK Registry Token
      requires:
        - release-precheck
  - check-api-compatibility:
      context:
        - Slack Orb
      requires:
        - build-baseline-sdk
        - build-dynamic
  - create-registry-pr:
      context:
        - Slack Orb
      requires:
        - build-static
        - build-docs
        - build-studio-preview
        - check-api-compatibility
  - wait-registry-pr:
      requires:
        - create-registry-pr
      type: approval
  - check-registry:
      context:
        - Slack Orb
        - SDK Registry Token
      requires:
        - wait-registry-pr
  - create-docs-prs:
      context:
        - Slack Orb
      requires:
        - check-registry
  - update-examples:
      context:
        - Slack Orb
        - Fastlane Match
        - SDK Registry Token
        - Apple Machine account
        - Maps SDK/Public Mapbox Token
      requires:
        - check-registry
  - publish-podspec:
      context:
        - Slack Orb
        - CocoaPods trunk token
      requires:
        - check-registry
  - validate-integrations:
      context:
        - Slack Orb
        - SDK Registry Token
      requires:
        - publish-podspec
  - create-draft-release:
      context:
        - Slack Orb
      requires:
        - create-docs-prs
        - update-examples
        - validate-integrations
