jobs:
  - release-precheck:
      context:
        - Slack Orb
        - SDK Registry Token
      filters: &release-filters
        tags:
          only: /^v[0-9]+\.[0-9]+\.[0-9]+.*/
        branches:
          ignore: /.*/
  - build-baseline-sdk:
      context:
        - Slack Orb
        - SDK Registry Token
      requires:
        - release-precheck
      filters: *release-filters
  - build-dynamic:
      check-api-breakage: true
      project-name: mobile-maps-ios
      context:
        - Slack Orb
        - SDK Registry Token
      requires:
        - release-precheck
      filters: *release-filters
  - build-static:
      context:
        - Slack Orb
        - SDK Registry Token
      requires:
        - release-precheck
      filters: *release-filters
  - build-docs:
      context:
        - Slack Orb
        - SDK Registry Token
      requires:
        - release-precheck
      filters: *release-filters
  - generate-docc:
      version: ${CIRCLE_TAG#v}-docc
      context:
        - Slack Orb
        - SDK Registry Token
      requires:
        - release-precheck
      filters: *release-filters
  - build-studio-preview:
      context:
        - Slack Orb
        - SDK Registry Token
      requires:
        - release-precheck
      filters: *release-filters
  - check-api-compatibility:
      context:
        - Slack Orb
      requires:
        - build-baseline-sdk
        - build-dynamic
      filters: *release-filters
  - create-registry-pr:
      project-name: mobile-maps-ios
      context:
        - Slack Orb
      requires:
        - build-static
        - build-docs
        - generate-docc
        - build-studio-preview
        - check-api-compatibility
      filters: *release-filters
  - check-registry:
      project-name: mobile-maps-ios
      context:
        - Slack Orb
        - SDK Registry Token
      requires:
        - create-registry-pr
      filters: *release-filters
  - create-docs-prs:
      context:
        - Slack Orb
      requires:
        - check-registry
      filters: *release-filters
  - update-examples:
      context:
        - Slack Orb
        - Fastlane Match
        - SDK Registry Token
        - Apple Machine account
        - Maps SDK/Public Mapbox Token
      requires:
        - check-registry
      filters: *release-filters
  - publish-podspec:
      context:
        - Slack Orb
        - CocoaPods trunk token
        - SDK Registry Token
      requires:
        - check-registry
      filters: *release-filters
  - validate-integrations:
      context:
        - Slack Orb
        - SDK Registry Token
      requires:
        - publish-podspec
      filters: *release-filters
  - create-draft-release:
      context:
        - Slack Orb
      requires:
        - create-docs-prs
        - update-examples
        - validate-integrations
      filters: *release-filters
