jobs:
  - build-dynamic:
      context:
        - Slack Orb
        - SDK Registry Token
      check-api-breakage: false
      project-name: mobile-maps-ios-preview
      filters: &release-filters
        tags:
          # matches v11.0.0-alpha
          only: /^v[0-9]+\.[0-9]+\.[0-9]+-alpha.*/
        branches:
          ignore: /.*/
  - create-registry-pr:
      project-name: mobile-maps-ios-preview
      skip-private-sdk: true
      context:
        - Slack Orb
      requires:
        - build-dynamic
      filters: *release-filters
  - wait-registry-pr:
      requires:
        - create-registry-pr
      type: approval
      filters: *release-filters
  - check-registry:
      project-name: mobile-maps-ios-preview
      context:
        - Slack Orb
        - SDK Registry Token
      requires:
        - wait-registry-pr
      filters: *release-filters
