when:
  or:
    - equal: [main, << pipeline.git.branch >>]
    - equal: [develop, << pipeline.git.branch >>]
    - << pipeline.git.tag >> # run for all tags
jobs:
  - build-benchmark:
      context:
        - SDK Registry Token
        - MapboxCI GitHub UserToken
        - Maps SDK/Public Mapbox Token
  - run-benchmark:
      requires:
        - build-benchmark
  - collect-metrics:
      requires:
        - run-benchmark

  - build-maps:
      context:
        - SDK Registry Token
      upload-size-metrics: true
