when:
  and:
    - equal: [ << pipeline.trigger_source >>, webhook ]
    - equal: [ << pipeline.git.branch >>, << pipeline.parameters.sdk_ci_repo_default_branch >> ]
jobs:
  - build-dynamic:
      name: build-snapshot
      context:
        - Slack Orb
        - SDK Registry Token
      check-api-breakage: false
      upload-type: snapshots
      project-name: mobile-maps-ios-preview