unless: << pipeline.parameters.turf-revision >>
jobs:
  - sanity-check:
      context:
        - Slack Orb
  - swiftlint:
      context:
        - Slack Orb
  - depsvalidator:
      context:
        - Slack Orb
      name: Check dependencies versions
  - build-sdk:
      context:
        - Slack Orb
        - SDK Registry Token
      name: Build SDK
      xcode: "13.1.0"
      configuration: "Release"

  - build-sdk-for-api-compatibility-check:
      context:
        - Slack Orb
        - SDK Registry Token
  - build-baseline-sdk:
      context:
        - Slack Orb
        - SDK Registry Token
  - check-api-compatibility:
      context:
        - Slack Orb
      requires:
        - build-sdk-for-api-compatibility-check
        - build-baseline-sdk
  - create-xcframework:
      context:
        - Slack Orb
        - SDK Registry Token
  - validate-integrations-for-branch:
      context:
        - Slack Orb
        - SDK Registry Token

  # Trigger mobile-metrics workflows
  - trigger-metrics-v2:
      context:
        - Slack Orb
        - Maps SDK/CircleCI API Token
  - trigger-binary-size:
      context:
        - Slack Orb
        - Maps SDK/CircleCI API Token
      requires:
        - Build SDK
  - trigger-metrics-build:
      context:
        - Slack Orb
        - Maps SDK/CircleCI API Token
      requires:
        - Build SDK
  - trigger-metrics-collection:
      context:
        - Slack Orb
        - Maps SDK/CircleCI API Token
      requires:
        - Build SDK
      filters:
        branches:
          only: main

  # Run unit tests on CI simulator
  - build-tests:
      context:
        - Slack Orb
        - SDK Registry Token
        - Maps SDK/Public Mapbox Token
      name: Build tests
  - run-unit-tests:
      context:
        - Slack Orb
      xcode: 14.1.0
      matrix:
        parameters:
          destination: ["OS=15.5,name=iPhone 13", "OS=16.1,name=iPhone 14"]
      requires:
        - Build tests
  - run-unit-tests:
      context:
        - Slack Orb
      xcode: 12.5.1
      disable_codecoverage: true
      matrix:
        parameters:
          destination: ["OS=13.7,name=iPhone 11", "OS=14.5,name=iPhone 11"]
      requires:
        - Build tests
  - run-integration-tests:
      context:
        - Slack Orb
      requires:
          - Build tests
      name: Run integration tests

  - build-tests:
      context:
        - Slack Orb
        - SDK Registry Token
        - Maps SDK/Public Mapbox Token
      name: build-tests-min-turf
      turf-revision: v2.0.0

  - run-unit-tests:
      context:
        - Slack Orb
      name: run-unit-tests-min-turf
      xcode: 13.1.0
      destination: OS=15.0,name=iPhone 12
      requires:
        - build-tests-min-turf

  # Build all tests with host application
  # Run on main by default
  # Can be approved to run on other branches
  - build-host-tests:
      context:
        - Slack Orb
        - Fastlane Match
        - SDK Registry Token
        - Apple Machine account
        - Maps SDK/Public Mapbox Token
      name: Build MapboxTestHost tests
  - run-firebase-tests:
      context:
        - Slack Orb
        - Maps SDK/Google Cloud credentials
      name: Run MapboxTestHost tests
      scheme: MapboxTestHost
      requires:
        - Build MapboxTestHost tests
      filters:
        branches:
          only: main

  # Build and Run tests on Examples scheme.
  # Enabled by-default on 'main' branch
  # Can be approved on purpose for others
  - build-examples-tests:
      context:
        - Slack Orb
        - Fastlane Match
        - SDK Registry Token
        - Apple Machine account
        - Maps SDK/Public Mapbox Token
      name: Build Examples tests
  - run-firebase-tests:
      context:
        - Slack Orb
        - Maps SDK/Google Cloud credentials
      name: Run Examples tests
      scheme: Examples
      requires:
        - Build Examples tests
      filters:
        branches:
          only: main

  # Notify internal CI about main and release branch updates
  - trigger-internal-ci-sync:
      context:
        - Slack Orb
        - Maps SDK/CircleCI API Token
      filters:
        branches:
          only:
            - main
            - /^release/v10.*/

  # Configure triggering end-to-end verification
  - sdk-e2e-test:
      context:
        - Slack Orb
        - Maps SDK/CircleCI API Token
      filters:
          branches:
              ignore:
                  - main
      name: run-sdk-e2e-test-devel
  - sdk-e2e-test:
      context:
        - Slack Orb
        - Maps SDK/CircleCI API Token
      filters:
          branches:
              only:
                  - main
          tags:
              only: /^v.*/
      name: run-sdk-e2e-test-validation
      validation: true
  - generate-docc:
      context:
        - Slack Orb
        - SDK Registry Token
        - Maps SDK/Public Mapbox Token
      filters:
        branches:
          only: main
  - upload-docc:
      context:
        - Slack Orb
      requires:
        - generate-docc
      filters:
        branches:
          only: main
